In [3]:
# For MyoGym
from MyoGymLoader import MyoGymLoader
myogym_loader = MyoGymLoader("../../../data/datasets/MyoGym.mat")
myogym_data_df, myogym_mapping = myogym_loader.load_data()

# For RecoFit
from RecoFitLoader import RecoFitLoader
recofit_loader = RecoFitLoader("../../../data/datasets/RecoFit")
recofit_data_df, recofit_mapping = recofit_loader.load_data()

In [4]:
myogym_mapping

{0: 'No activity identified',
 1: 'Seated Cable Rows',
 2: 'One-Arm Dumbbell Row',
 3: 'Wide-Grip Pulldown Behind The Neck',
 4: 'Bent Over Barbell Row',
 5: 'Reverse Grip Bent-Over Row',
 6: 'Wide-Grip Front Pulldown',
 7: 'Bench Press',
 8: 'Incline Dumbbell Flyes',
 9: 'Incline Dumbbell Press',
 10: 'Dumbbell Flyes',
 11: 'Pushups',
 12: 'Leverage Chest Press',
 13: 'Close-Grip Barbell Bench Press',
 14: 'Bar Skullcrusher',
 15: 'Triceps Pushdown',
 16: 'Bench Dip / Dip',
 17: 'Overhead Triceps Extension',
 18: 'Tricep Dumbbell Kickback',
 19: 'Spider Curl',
 20: 'Dumbbell Alternate Bicep Curl',
 21: 'Incline Hammer Curl',
 22: 'Concentration Curl',
 23: 'Cable Curl',
 24: 'Hammer Curl',
 25: 'Upright Barbell Row',
 26: 'Side Lateral Raise',
 27: 'Front Dumbbell Raise',
 28: 'Seated Dumbbell Shoulder Press',
 29: 'Car Drivers',
 30: 'Lying Rear Delt Raise'}

In [5]:
recofit_mapping

{0: '<Initial Activity>',
 1: 'Alternating Dumbbell Curl',
 2: 'Arm Band Adjustment',
 3: 'Arm straight up',
 4: 'Band Pull-Down Row',
 5: 'Bicep Curl',
 6: 'Biceps Curl (band)',
 7: 'Box Jump (on bench)',
 8: 'Burpee',
 9: 'Butterfly Sit-up',
 10: 'Chest Press (rack)',
 11: 'Crunch',
 12: 'Device on Table',
 13: 'Dip',
 14: 'Dumbbell Deadlift Row',
 15: 'Dumbbell Row (knee on bench) (label spans both arms)',
 16: 'Dumbbell Row (knee on bench) (left arm)',
 17: 'Dumbbell Row (knee on bench) (right arm)',
 18: 'Dumbbell Squat (hands at side)',
 19: 'Dynamic Stretch (at your own pace)',
 20: 'Elliptical machine',
 21: 'Fast Alternating Punches',
 22: 'Invalid',
 23: 'Jump Rope',
 24: 'Jumping Jacks',
 25: 'Kettlebell Swing',
 26: 'Lateral Raise',
 27: 'Lawnmower (label spans both arms)',
 28: 'Lawnmower (left arm)',
 29: 'Lawnmower (right arm)',
 30: 'Lunge (alternating both legs, weight optional)',
 31: 'Medicine Ball Slam',
 32: 'Non-Exercise',
 33: 'Note',
 34: 'Overhead Triceps Extension',
 35: 'Overhead Triceps Extension (label spans both arms)',
 36: 'Plank',
 37: 'Power Boat pose',
 38: 'Pushup (knee or foot variation)',
 39: 'Pushups',
 40: 'Repetitive Stretching',
 41: 'Rest',
 42: 'Rowing machine',
 43: 'Running (treadmill)',
 44: 'Russian Twist',
 45: 'Seated Back Fly',
 46: 'Shoulder Press (dumbbell)',
 47: 'Side Plank Left side',
 48: 'Side Plank Right side',
 49: 'Sit-up (hands positioned behind head)',
 50: 'Sit-ups',
 51: 'Squat',
 52: 'Squat (arms in front of body, parallel to ground)',
 53: 'Squat (hands behind head)',
 54: 'Squat (kettlebell / goblet)',
 55: 'Squat Jump',
 56: 'Squat Rack Shoulder Press',
 57: 'Static Stretch (at your own pace)',
 58: 'Static stretch',
 59: 'Tap IMU Device',
 60: 'Tap Left Device',
 61: 'Tap Right Device',
 62: 'Triceps Kickback (knee on bench) (label spans both arms)',
 63: 'Triceps Kickback (knee on bench) (left arm)',
 64: 'Triceps Kickback (knee on bench) (right arm)',
 65: 'Triceps extension (lying down)',
 66: 'Triceps extension (lying down) (left arm)',
 67: 'Triceps extension (lying down) (right arm)',
 68: 'Two-arm Dumbbell Curl (both arms, not alternating)',
 69: 'Unknown',
 70: 'Unlisted Exercise',
 71: 'V-up',
 72: 'Walk',
 73: 'Walking lunge',
 74: 'Wall Ball',
 75: 'Wall Squat'}

In [6]:
myogym_data_df

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,activity,trainer,time
64730,-0.791504,0.595703,0.054199,38.5625,-15.9375,12.6250,0,1,0.00
64731,-0.781250,0.603516,0.031250,44.8125,-19.5625,19.2500,0,1,0.02
64732,-0.764648,0.622559,0.020020,48.5625,-21.3125,23.6875,0,1,0.04
64733,-0.751465,0.649414,0.011719,50.6875,-22.3750,24.2500,0,1,0.06
64734,-0.765137,0.670410,-0.008301,52.0625,-23.7500,21.0625,0,1,0.08
...,...,...,...,...,...,...,...,...,...
1911834,-0.645508,0.797363,-0.219238,10.1250,8.8125,-1.2500,0,10,2087.48
1911835,-0.628906,0.681641,-0.226563,-10.9375,3.0625,1.7500,0,10,2087.50
1911836,-0.678223,0.708008,-0.219238,-10.3750,-0.7500,2.0000,0,10,2087.52
1911838,-0.611328,0.641602,-0.176270,-17.2500,-4.7500,5.6875,0,10,2087.54
1911839,-0.656738,0.624023,-0.191895,2.3750,-2.6875,7.9375,0,10,2087.56

In [7]:
recofit_data_df

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,activity,trainer,time
0,-1.053396,-0.240851,0.007644,-6.320330,-38.337973,-16.067351,0,0,0.000
1,-1.035112,-0.206829,-0.015404,2.997305,-49.883744,-17.257456,0,0,0.020
2,-0.971612,-0.175238,0.008482,2.541084,-61.131924,-16.663252,0,0,0.040
3,-0.905299,-0.147946,0.044365,-8.750498,-67.743795,-14.327861,0,0,0.060
4,-0.887257,-0.135992,0.091578,-21.993410,-69.473844,-11.848797,0,0,0.080
...,...,...,...,...,...,...,...,...,...
14295600,-0.261000,0.351041,0.807325,-6.851228,3.066831,-3.437496,12,125,2558.269
14295601,-0.263873,0.352947,0.809510,-6.891108,3.072903,-3.451624,12,125,2558.289
14295602,-0.260786,0.350253,0.804076,-6.906065,3.132749,-3.482305,12,125,2558.309
14295603,-0.267537,0.358723,0.836679,-7.173825,3.200092,-3.632732,12,125,2558.329
14295604,-0.142877,0.191596,0.446292,-3.811434,1.666538,-1.941868,12,125,2558.349